import {useEffect,useRef,useState} from 'react'
import {Captions,Upload} from 'lucide-react'
import {parseSubtitles} from '../../utils/subtitles'
export default function SubtitleTools({videoId,host}){
    const [cues,setCues]=useState([]),[enabled,setEnabled]=useState(true),[text,setText]=useState(''),[open,setOpen]=useState(false),[error,setError]=useState('')
    const input=useRef(null)
    useEffect(()=>{setText('');setError('');setOpen(false);try{setCues(JSON.parse(localStorage.getItem('tutin_subtitles_'+videoId))||[])}catch{setCues([])}},[videoId])
    useEffect(()=>{if(!enabled||!cues.length){setText('');return}const tick=()=>{const video=host.current?.querySelector('video');if(!video){setText('');return}const time=video.currentTime;setText(cues.filter(cue=>time>=cue.start&&time<cue.end).map(cue=>cue.text).join('\n'))};tick();const timer=setInterval(tick,250);return()=>clearInterval(timer)},[cues,enabled,host])
    async function upload(event){const file=event.target.files?.[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('Subtitle file must be smaller than 2 MB.');const parsed=parseSubtitles(await file.text());localStorage.setItem('tutin_subtitles_'+videoId,JSON.stringify(parsed));setCues(parsed);setEnabled(true);setError('')}catch(err){setError(err.message)}event.target.value=''}
    return <><div className="absolute top-2 right-2 z-30"><button aria-label="Subtitle options" title="Subtitles" onClick={()=>setOpen(!open)} className="rounded-full bg-black/60 p-2 text-white hover:bg-black/80"><Captions className="h-5 w-5"/></button>{open&&<div className="mt-2 max-w-64 rounded-lg bg-neutral-900 p-3 text-white shadow-xl"><input ref={input} type="file" accept=".srt,.vtt" onChange={upload} className="hidden"/><button onClick={()=>input.current.click()} className="flex items-center gap-2 text-xs"><Upload className="h-4 w-4"/>Import SRT / VTT</button>{cues.length>0&&<button onClick={()=>setEnabled(!enabled)} aria-pressed={enabled} className="mt-3 block text-xs">{enabled?'Turn subtitles off':'Turn subtitles on'}</button>}<p className="mt-2 text-[10px] text-neutral-400">For local and resumable Drive playback.</p>{error&&<p role="alert" className="mt-2 text-xs text-red-400">{error}</p>}</div>}</div>{text&&<div className="pointer-events-none absolute bottom-24 inset-x-4 z-20 text-center"><span className="inline-block whitespace-pre-line rounded bg-black/80 px-3 py-2 text-sm sm:text-lg text-white">{text}</span></div>}</>
}
